### PR TITLE
css-canvas-medical - Chase Simmonds

### PR DESCRIPTION
**Pull request by chase-simmonds**
Screen Shot 2022-05-16 at 2 47 34 AM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Chase, this doesn't match the example output. Please do not submit your code until it matches the output expected perfectly. If you are unable to meet a deadline, you can just let me know via Slack.

**Comment by chase-simmonds** [comment]
Screen Shot 2022-05-22 at 11 34 45 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Chase, the text color of your buttons doesn't match the example, please revise. When you resubmit, make sure you include screenshots that showcase the current state of the entire output.

**Comment by chase-simmonds** [comment]
screencapture-127-0-0-1-5500-css-canvas-medical-index-html-2022-05-23-14_42_10

**Review by codingcodymiller — APPROVED** [review]
_**Excellent work**_ 👏 👏 👏

**Pull request merged**
